import cn.hutool.core.annotation.CacheableSynthesizedAnnotationAttributeProcessor;
public class FunctionUse118 {
public void funcUse() {
CacheableSynthesizedAnnotationAttributeProcessor cacheablesynthesizedannotationattributeprocessor = new CacheableSynthesizedAnnotationAttributeProcessor();
cacheablesynthesizedannotationattributeprocessor.getAttributeValue(null,null,null);
}
}